ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5,4) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(10,2) DEFAULT 0;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5,4) DEFAULT 0;
